# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/alex/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# The following lines were added by alex
autoload -U colors && colors

PS1="%B%F{#00ff00}--> %# "

# Colors for prompt
idcolor="%B%F{#8700ff}"
idcolor="%B%F{#875fd7}"
dircolor="%B%F{#ffd700}"
promptcolor="%B%F{#d70000}"

# Set my standard prompt
PS1="${idcolor}%n@%m ${dircolor}%~${promptcolor}%#$reset_color "

# If Im in tmux
if { [ "$TMUX" ]; } then
  PS1="${idcolor}==> ${dircolor}%~${promptcolor}%#$reset_color "
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias dir='dir --color=auto'
  alias vdir='vdir --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

source $HOME/.bash_aliases



# End of lines configured by alex
