# Aliases
alias tmuxnew='tmux new -s A10X'
alias lsla='ls -lash'
alias c='clear'
alias blink="printf '\e[?12h'"
alias blinkbar="printf '\033[6 q' ; printf '\e[?12h'"
alias bb=blinkbar

# Systemctl
alias screstart='sudo systemctl restart'
alias scstatus='sudo systemctl status'
alias scenable='sudo systemctl enable'
alias scstop='sudo systemctl stop'
alias scstart='sudo systemctl start'

# nnn
alias nnn='nnn -CEDHUdei'
alias sudonnn='sudo -E nnn -CEDHUdei'
# no -i (file info)
alias nnn='nnn -CEDHUde'
alias sudonnn='sudo -E nnn -CEDHUde'
# Shows the level when using ! to spawn a terminal in nnn
[ -n "$NNNLVL" ] && PS1="N$NNNLVL $PS1"

# SSH

# Start and stop the ssh-agent
alias sshon='eval "$(ssh-agent -s)" > /dev/null'
alias sshoff='eval "$(ssh-agent -k)" > /dev/null'

# Adds my keys to agent if present
function sshme(){
  # If my key is on the system
  if [[ -f ~/.ssh/id_ed25519_github ]]; then
    ssh-add ~/.ssh/id_ed25519_github &> /dev/null
    ssh-add ~/.ssh/id_ed25519 &> /dev/null
  fi
}

# Exports
# Select a text editor (nano as last resort)
export EDITOR=nano
# If we have vim then use that
if command -v vim &> /dev/null
then
  export EDITOR=vim
fi
alias vi='vim'
# If we have neovim, ditch vim
if command -v nvim &> /dev/null
then
  export EDITOR=nvim
  alias vim='nvim'
fi

function alex(){
 PS1="\[\033[1;31m\]\u@\h \[\033[0;34m\]\w\[\033[0;37m\]\$\[\033[0m\] " 
}

# Git
if command -v git &> /dev/null
then
  git config --global user.name "arydningen"
  git config --global user.email "arydningen@gmail.com"
fi

function gitme(){
  # If my key is on the system
  if [[ -f ~/.ssh/id_ed25519_github ]]; then
    #eval "$(ssh-agent -s)" > /dev/null
    ssh-add ~/.ssh/id_ed25519_github &> /dev/null
  fi
}

# Finds tagged hosts Usage
# function ssh-hosts-tag() {
#   sed -n -e "/# $1/,/# / p" ~/.ssh/config
# }

# alias ssh-hosts="grep -P \"^Host ([^*]+)$\" $HOME/.ssh/config | sed 's/Host //'"

